# Generated by Django 4.2.6 on 2023-10-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(max_length=50, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=500)),
                ('detalle_corto', models.CharField(max_length=200)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entidad')),
            ],
        ),
    ]
