# Generated by Django 4.2.6 on 2023-10-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
